openapi: 3.0.0
info:
  title: Campus Delivery API
  description: MVP API for a university campus food delivery service
  version: 1.0.0

paths:
  /api/users/me:
    get:
      summary: Get current user profile
      description: Retrieves the authenticated user's profile from Clerk
      security:
        - BearerAuth: []

    put:
      summary: Update user profile
      description: Allows a user to update their profile details
      security:
        - BearerAuth: []

  /api/orders:
    post:
      summary: Place an order
      description: Allows a customer to place an order for delivery
      security:
        - BearerAuth: []

    get:
      summary: Get orders
      description: Customers see their own orders; delivery people see available orders
      security:
        - BearerAuth: []

  /api/orders/{orderId}:
    get:
      summary: Get order details
      description: Retrieves details for a specific order
      security:
        - BearerAuth: []

  /api/orders/{orderId}/accept:
    post:
      summary: Accept an order
      description: Allows a delivery person to accept an available order
      security:
        - BearerAuth: []

  /api/orders/{orderId}/status:
    put:
      summary: Update order status
      description: Allows the delivery person or customer to update order status
      security:
        - BearerAuth: []

  /api/orders/{orderId}/confirm:
    post:
      summary: Confirm order delivery
      description: Customer confirms receipt, triggering payment settlement
      security:
        - BearerAuth: []

  /api/orders/{orderId}/cancel:
    put:
      summary: Cancel an order
      description: Cancels an order if within allowed conditions
      security:
        - BearerAuth: []

  /api/payments/initiate:
    post:
      summary: Initiate payment
      description: Authorizes and holds funds for an order
      security:
        - BearerAuth: []

  /api/payments/complete:
    post:
      summary: Complete payment
      description: Processes final payment settlement upon order confirmation
      security:
        - BearerAuth: []

  /api/payments/{orderId}:
    get:
      summary: Get payment details
      description: Retrieves payment status for a specific order
      security:
        - BearerAuth: []

  /api/orders/{orderId}/feedback:
    post:
      summary: Submit feedback
      description: Allows users to leave feedback after order completion
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []